[project]
name = "sc-knockout-analysis"
version = "0.1.0"
description = "Quick single-cell knockout analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["helical>=1.8.0", "ipykernel>=7.2.0", "ipywidgets>=8.1.8", "scanpy>=1.11"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true
